[versions]
kotlin = "2.2.21"

[libraries]
spring-modulith-bom     = { module = "org.springframework.modulith:spring-modulith-bom",  version = "2.0.0"  }
spring-ai-bom           = { module = "org.springframework.ai:spring-ai-bom",              version = "1.1.1"  }

converter-html2markdown = { module = "com.vladsch.flexmark:flexmark-html2md-converter",   version = "0.64.8" }
maven-resolver-supplier = { module = "org.apache.maven.resolver:maven-resolver-supplier", version = "1.9.24" }
maven-resolver-provider = { module = "org.apache.maven:maven-resolver-provider",          version = "3.9.11" }
kotlin-logging          = { module = "io.github.oshai:kotlin-logging-jvm",                version = "7.0.13" }

test-assertj            = { module = "org.assertj:assertj-core",                          version = "3.27.6" }
test-mockitoKotlin      = { module = "org.mockito.kotlin:mockito-kotlin",                 version = "6.1.0"  }

[plugins]
kotlin-jvm    = { id = "org.jetbrains.kotlin.jvm",           version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot   = { id = "org.springframework.boot",           version = "4.0.0"      }
graalvm       = { id = "org.graalvm.buildtools.native",      version = "0.11.3"     }